---
- name: set up web server
  hosts: all
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: create index file
      copy:
        dest: /var/www/html/index.html
        content: "Welcome to my web server"

    - name: start httpd
      service:
        name: httpd
        state: started
        enabled: yes

    - name: install firewalld
      yum:
        name: firewalld
        state: latest

    - name: add ports with firewalld
      firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
      loop:
        - 8080/tcp
        - 80/tcp
        - 443/tcp
      notify: reload firewalld

  handlers:
    - name: reload firewalld
      service:
        name: firewalld
        state: reloaded
